/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:9caaebfb-2877-4653-8e70-b4c404e80d51",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_uKCg2lifD",
    "aws_user_pools_web_client_id": "5tpmcalr77k8fuac5l1crcpk1p",
    "oauth": {}
};


export default awsmobile;
